In [2]:
import numpy as np

In [3]:
n = np.random.randn(3,5)
print(n)
n.tofile('n.npy')

[[-0.03617418 -0.73458597 -0.02506726 -0.01321246 -0.85569237]
 [-0.63501333  0.55999487 -0.5386968   0.091805   -1.17119426]
 [ 1.16655155 -0.66508996 -0.68519324 -1.01036698  0.22289377]]


In [4]:
m = np.fromfile('n.npy').reshape(3,5) # shape(3,5)
print(m)

[[-0.03617418 -0.73458597 -0.02506726 -0.01321246 -0.85569237]
 [-0.63501333  0.55999487 -0.5386968   0.091805   -1.17119426]
 [ 1.16655155 -0.66508996 -0.68519324 -1.01036698  0.22289377]]


In [5]:
np.save('n1.npy',n)
m1 = np.load('n1.npy')
print(m1)

[[-0.03617418 -0.73458597 -0.02506726 -0.01321246 -0.85569237]
 [-0.63501333  0.55999487 -0.5386968   0.091805   -1.17119426]
 [ 1.16655155 -0.66508996 -0.68519324 -1.01036698  0.22289377]]


In [6]:
# n.tofile로 만든 n.npy는 np.load로 열리지않음
# no.tofile - no.fromfile
# np.save - np.load
np.load('n.npy')

ValueError: Cannot load file containing pickled data when allow_pickle=False

In [15]:
np.savetxt('n.txt',n)
np.loadtxt('n.txt', dtype = str)

array([['-3.617417880241372702e-02', '-7.345859715562542691e-01',
        '-2.506725900229291384e-02', '-1.321246399145614009e-02',
        '-8.556923712149462347e-01'],
       ['-6.350133324946821700e-01', '5.599948717021822064e-01',
        '-5.386967951327155113e-01', '9.180499522844888516e-02',
        '-1.171194261597337860e+00'],
       ['1.166551547348195772e+00', '-6.650899624000465860e-01',
        '-6.851932355804999375e-01', '-1.010366976400092209e+00',
        '2.228937680217256689e-01']], dtype='<U25')

In [14]:
# np.savetxt('n.csv',n) csv파일이지만 공백으로 값이 구분됨
np.savetxt('n.csv', n, delimiter = ',') # 값의 구분자를 ,로 지정
np.loadtxt('n.csv', delimiter = ',')

array([[-0.03617418, -0.73458597, -0.02506726, -0.01321246, -0.85569237],
       [-0.63501333,  0.55999487, -0.5386968 ,  0.091805  , -1.17119426],
       [ 1.16655155, -0.66508996, -0.68519324, -1.01036698,  0.22289377]])

In [36]:
# 1번 문제
a = np.arange(1,26).reshape(5,5)
np.savetxt('data.csv', a, delimiter = ',')
np.loadtxt('data.csv', delimiter = ',', dtype = int8)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [41]:
# 2번 문제
arr1 = np.loadtxt('C:/DEV/STUDY/StudyPython22.05/data/06_data1.txt', delimiter = '\t', dtype = str) # 구분자가 tab으로 되어있음
print(arr1)

[['1' '15' '14' '4']
 ['12' '6' '7' '9']
 ['8' '10' '11' '5']
 ['13' '3' '2' '16']]


In [44]:
# 3번 문제
arr2 = np.loadtxt('C:/DEV/STUDY/StudyPython22.05/data/06_data2.txt', delimiter = ',', dtype=np.int8)
print(arr2)

[[ 1 15 14  4]
 [12  6  7  9]
 [ 8 10 11  5]
 [13  3  2 16]]


In [48]:
## 파일 처리
# 1)파일 읽어오기
data = np.loadtxt('C:/DEV/STUDY/StudyPython22.05/data/ex1_지역별전기요금.csv', 
                  delimiter = ',', 
                  dtype = int)
print(data[:5,:]) # 상위 5개 데이터 출력

[[      1  565082     273   27177]
 [      2 2827233     444   45111]
 [      3 1144913     289   29043]
 [      4 1131034     230   22436]
 [      5  380425     391   38020]]


In [67]:
# 2) 데이터 모양 확인
print(data.shape)

# 중복 지역 확인
print(np.unique(data[:,0]))

(17, 4)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [68]:
# 데이터의 크기순 정렬 (argsort 사용)
print(data[:,1].argsort()) # 값의 크기 오름차순으로 정렬하여 index를 뽑아줌
print(data[:,1].argsort()[::-1]) # 내림차순

# fancy index
print(data[data[:,1].argsort()])
print(data[data[:,1].argsort()[::-1]]) # 내림차순

[ 9 14 10  4  6  0 16 13  5 12 11 15  7  3  2  8  1]
[ 1  8  2  3  7 15 11 12  5 13 16  0  6  4 10 14  9]
[[     10   49394     580   57091]
 [     15  258605     221   22180]
 [     11  323151     353   35470]
 [      5  380425     391   38020]
 [      7  425659     344   32331]
 [      1  565082     273   27177]
 [     17  584500     268   26899]
 [     14  634696     285   28556]
 [      6  668623     364   35245]
 [     13  726699     249   25120]
 [     12  734723     398   40049]
 [     16  742285     282   27901]
 [      8  947300     366   36274]
 [      4 1131034     230   22436]
 [      3 1144913     289   29043]
 [      9 2737725     361   36569]
 [      2 2827233     444   45111]]
[[      2 2827233     444   45111]
 [      9 2737725     361   36569]
 [      3 1144913     289   29043]
 [      4 1131034     230   22436]
 [      8  947300     366   36274]
 [     16  742285     282   27901]
 [     12  734723     398   40049]
 [     13  726699     249   25120]
 [      6  668623 

In [69]:
# 3) 데이터 통계
# 전국 대상 가구수의 합
print(np.sum(data[:,1]))

# 가구당 평균 전력 사용량의 전국 평균값
print(round(data[:,2].mean(), 2))

# 평균 구하기(좋지않은 방법?)
e_sum = np.sum(data[:,2])
n_rows = data.shape[0]
print(round(e_sum / n_rows,2))

14882047
335.18
335.18


In [111]:
# 가구당 평균 전력 사용량이 평균 이상인 지역과 대상 가구수 추출
avg = data[:,2].mean() # 가구당 평균 전력 사용량의 전국 평균
print(data[data[:,2]>=avg, 0:2])

[[      2 2827233]
 [      5  380425]
 [      6  668623]
 [      7  425659]
 [      8  947300]
 [      9 2737725]
 [     10   49394]
 [     11  323151]
 [     12  734723]]


In [146]:
## 파일2 직접 해보기
# 1번 문제 위 파일을 읽어오고 상위 3개의 (발생년도, 발생건수, 구성비) 데이터를 추출하기
data2 = np.loadtxt('C:/DEV/STUDY/StudyPython22.05/data/ex2_전년대비_시도별_교통사망사고.csv', delimiter = ',')
print(data2.shape)
print(np.unique(data2[:,1]))
print(data2[:3,[0,2,3]])

(17, 6)
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.]
[[2014.   218.     4.8]
 [2014.   872.    19. ]
 [2014.   401.     8.7]]


In [148]:
# 2번 문제 부산에서 발생한 교통사망사고 모든 현황을 추출하기
print(data2[data2[:,1]==8,:])

[[2014.     8.   163.     3.6  -47.   -22.4]]


In [90]:
# 3번 문제 전국 사고 발생건수의 합계와 전국 평균 계산하기
# 합계
print(data2[:,2].sum())
# 평균
print(round(data2[:,2].mean(),2))

4583.0
269.59


In [93]:
# 4번 문제 교통사고 증감수가 가장 큰 지역의 모든 현황을 추출하기
print(data2[data2[:,4].argmax(),:])

[2014.     6.   182.     4.    19.    11.7]


In [95]:
# 5번 문제 교통사고 증감률이 가장 작은 지역의 모든 현황을 추출하기
print(data2[data2[:,5].argmin(),:])

[2014.     8.   163.     3.6  -47.   -22.4]


In [143]:
# 6번 문제 사고 발생 건수가 400건 이상인 곳의 지역과 교통사고 발생건수, 증감수, 증감률을 추출하기
a = data2[data2[:,2] >= 400, :]
print(a[:,[1,2,4,5]])

[[  2.  872.  -45.   -4.9]
 [  3.  401.  -45.  -10.1]
 [  4.  464.  -41.   -8.1]
 [ 13.  400.  -35.   -8. ]]
