In [1]:
import numpy as np

In [4]:
a = np.array(1)
a

array(1)

In [5]:
ndarr_1 = np.array([1,2,3])
print(ndarr_1)

[1 2 3]


In [6]:
ndarr_2 = np.array([1,2.0,3])
print(ndarr_2)

[1. 2. 3.]


In [7]:
ndarr_3 = np.array([1,2.0,'3'])
print(ndarr_3)

['1' '2.0' '3']


In [8]:
print(ndarr_1.dtype)
print(ndarr_2.dtype)
print(ndarr_3.dtype)

int32
float64
<U32


In [9]:
print(np.array(1+2j).dtype)
print(np.array(print).dtype)

complex128
object


In [10]:
dtype1 = np.array([1,2,3], dtype=np.int8)
print(dtype1.dtype)

int8


In [14]:
dtype2 = np.array([1,2,3], dtype=float)
print(dtype2.dtype)

float64


In [12]:
dtype3 = np.array([1,2,3], dtype=str)
print(dtype3.dtype)

<U1


In [15]:
dtype4 = np.array([1,2.1,'3'], dtype=int)
print(dtype4)
print(dtype4.dtype)

[1 2 3]
int32


In [17]:
dtype5 = np.array([1,'data',print], dtype=float)
print(dtype5.dtype)
# 문자열은 어떤 숫자로 바꿔야할지 모르기 때문에 에러

ValueError: could not convert string to float: 'data'

In [18]:
print(ndarr_1.shape)

(3,)


In [19]:
print(ndarr_1.ndim)

1


In [24]:
# 1차원 배열 생성

vector = np.array([1,2,3])
print(vector)
print(vector.shape)
print(vector.ndim)
print(vector.dtype)

[1 2 3]
(3,)
1
int32


In [25]:
# 2차원 배열 생성

matrix = np.array([[1,2,3],[4,5,6,]])
print(matrix)
print(matrix.shape)
print(matrix.ndim)
print(matrix.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int32


In [29]:
# 3차원 배열 생성
# 덩어리는 꼭 같은 숫자로 나눠져야되는건가?

tensor = np.array([[[1,2,3],[4,5,6,]],[[7,8,9],[10,11,12]]])
print(tensor)
print(tensor.shape)
print(tensor.ndim)
print(tensor.dtype)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
3
int32


In [30]:
print(vector.size)
print(matrix.size)
print(tensor.size)

3
6
12


In [35]:
matrix = np.array([[1,2,3],[2,4,6],[3,6,9]])
print(matrix)
print(matrix.ndim)
print(matrix.size)
print(matrix.shape)

[[1 2 3]
 [2 4 6]
 [3 6 9]]
2
9
(3, 3)


In [45]:
# 리스트에서 ndarray 변환

list1 = [1,2,3]
arr1 = np.array(list1)
print(type(arr1))

<class 'numpy.ndarray'>


In [46]:
# nparray에서 리스트로 변환

arr2 = np.array([1,2,3])
list2 = list(arr2)
print(list2, type(list2))

[1, 2, 3] <class 'list'>


In [49]:
list3 = [[1,2,3],[4,5,6]]
arr3 = np.array(list3)
print(arr3, type(arr3))

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>


In [53]:
# ndarray에서 리스트로 변환

list4 = [[1,2,3,4],[4,5,6]]
arr4 = np.array(list4)
print(arr4)
print(arr4.size, arr4.shape, arr4.ndim)

[list([1, 2, 3, 4]) list([4, 5, 6])]
2 (2,) 1


C:\Users\admin\AppData\Local\Temp\ipykernel_6312\533251202.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr4 = np.array(list4)


In [54]:
tuple1 = (1,2,3)
arr = np.array(tuple1)
print(arr)

[1 2 3]


In [55]:
arr2 = np.array([1,2,3])
tuple2 = tuple(arr2)
print(tuple2)

(1, 2, 3)


In [66]:
# 세트는 np.array로 변환이 되지않음(1묶음으로 통째로 변환)
set1 = {1,2,3}
arr = np.array(set1)
print(arr, arr.size, arr.shape)
# 스칼라가 됬기 때문에 shape 수행시 0으로 나옴

{1, 2, 3} 1 ()


In [64]:
dict1 = {'a':1,'b':2,'c':3}
arr = np.array(dict1)
print(arr, arr.size, arr.shape)
# 세트와 마찬가지로 스칼라가 됬기 때문에 shape 수행시 0으로 나옴

{'a': 1, 'b': 2, 'c': 3} 1 ()


In [69]:
list_ = [[[1,2],[3,4]],[[5,6],[7,8]]]

# 1 가져오기
print(list_[0][0][0])

# 4 가져오기
print(list_[0][1][1])

# 7 가져오기
print(list_[1][1][0])

1
4
7


In [76]:

arr_ = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

# 1 가져오기
print(arr_[0,0,0])
print(arr_[0][0][0])

# 4 가져오기
print(arr_[0,1,1])

# 7 가져오기
print(arr_[1,1,0])

1
1
4
7


In [77]:
# ndarray[rank, row, col]

arr_1 = np.array([[1,2],      # 2 x 3 형태의 2차원 배열
                  [3,4],
                  [5,6]])

# 0행 가져와 2차원 배열 만들기
print(arr_1[[0]]) # = print(arr_1[[0],:])

# 0, 2행 가져와 2차원 배열 만들기
# ndarray[[row1, row2], col]
print(arr_1[[0,2]]) # = print(arr_1[[0,2],:])

# 다음 결과는?
print(arr_1[[0,1,2],
            [0,1,0]])

# 같은 위치 데이터 여러 번 사용가능
print(arr_1[[0,0],
            [1,1]])

[[1 2]]
[[1 2]
 [5 6]]
[1 4 5]
[2 2]


In [82]:
arr_2 = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9],
                  [10,11,12]])

# 두 개의 차원 배열 만들기
b = np.array([0,1,2,3])
c = np.array([0,2,0,1])

# 다음 코드의 실행 결과는?
print(arr_2[b,c])

[ 1  6  7 11]


In [86]:
arr = np.array([1,2,3,4,5])

arr[arr % 3 == 0]

array([3])

In [92]:
score = np.array([[78,91,84,89,93,65],
                  [82,87,96,79,91,73]])
print(score[0][score[0] >= 90])
print(score[1][score[1] >= 90])

[91 93]
[96 91]


In [2]:
matrix = np.array([[1,2,3,4,5],
                   [6,7,8,9,10],
                   [11,12,13,14,15],
                   [16,17,18,19,20]])

In [6]:
#0열 전체 슬라이싱
print(matrix[:,0])

#0열 전체 슬라이싱 (2차원 유지)
print(matrix[:,:1])

[ 1  6 11 16]
[[ 1]
 [ 6]
 [11]
 [16]]


In [15]:
# 1행 전체 슬라이싱
print(matrix[1])
print(matrix[1,])
print(matrix[1,:]) # rank > row > col 순으로 :(콜론) 생략 가능

# 1행 전체 슬라이싱 (2차원 유지)
print(matrix[1:2,:]) # or print(matrix[[1]])

[ 6  7  8  9 10]
[ 6  7  8  9 10]
[ 6  7  8  9 10]
[[ 6  7  8  9 10]]


In [16]:
# 3~4열 전체 슬라이싱
print(matrix[:,3:])

[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]]


In [19]:
# 0행, 1~3열 슬라이싱
print(matrix[0,1:-1])
print(matrix[0,1:4])

[2 3 4]
[2 3 4]


In [23]:
# 2~3행, 2~4열 슬라이싱
print(matrix[-2:,-3:])

# 1~2행, 1~2열 슬라이싱
print(matrix[1:3,1:3]) # or matrix[1:-1,1:3]

[[13 14 15]
 [18 19 20]]
[[ 7  8]
 [12 13]]


In [24]:
# 1, 3행, 2~4열 슬라이싱
print(matrix[[1,3],2:])

# 1~2행, 1, 3열 슬라이싱
print(matrix[1:-1,[1,3]])

[[ 8  9 10]
 [18 19 20]]
[[ 7  9]
 [12 14]]


In [41]:
tensor = np.array([[[1,2,3],
                    [4,5,6]],
                   [[7,8,9],
                    [10,11,12]]])
print(tensor)
print(tensor[[1,0,0],[1,0,1],[0,1,2]])
print(tensor[0,:,:2])
print(tensor[1,:,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[10  2  6]
[[1 2]
 [4 5]]
[ 9 12]
