In [13]:
import numpy as np

In [14]:
# 요소 개수에 맞게 입력해줘야 함
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.reshape(3,2))
print(arr.reshape(1,6))
print(arr.reshape(6,1))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [15]:
# 3 x 1 x 2  배열로 변형
print(arr.reshape(3,1,2))

# ? x 2 배열로 변형(열은 맞추고 싶은데 행개수는 모를때)
print(arr.reshape(-1,2))

# 차원줄이기
print(arr.reshape(6,))

[[[1 2]]

 [[3 4]]

 [[5 6]]]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [24]:
tensor = np.array(range(1,37)) # shape (3,3,4)
tensor.reshape(3,3,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]]])

In [26]:
tensor = tensor.reshape(-1,9)
tensor

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36]])

In [28]:
print(arr.flatten())
print(arr.reshape(1,6).flatten())
print(arr.reshape(3,1,2).flatten())

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [45]:
print(np.arange(30))
print(np.arange(0,10,2))
print(np.arange(-2,2.5,0.5))
print(np.arange(10,0,-1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[0 2 4 6 8]
[-2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2. ]
[10  9  8  7  6  5  4  3  2  1]


In [38]:
print(np.arange(1,26).reshape(5,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [42]:
print(np.arange(100,191,10).reshape(2,5))

[[100 110 120 130 140]
 [150 160 170 180 190]]


In [49]:
print(np.arange(-2,2.5,0.5).size)
print(np.arange(-2,2.5,0.5).reshape(3,1,3))

9
[[[-2.  -1.5 -1. ]]

 [[-0.5  0.   0.5]]

 [[ 1.   1.5  2. ]]]


In [55]:
print(np.zeros(shape=(5,),dtype=np.int8))
print(np.zeros((5),int)) # shape이기때문에 괄호가 들어가야함
print(np.zeros((2,3)))

[0 0 0 0 0]
[0 0 0 0 0]
[[0. 0. 0.]
 [0. 0. 0.]]


In [56]:
print(np.ones(shape=(5,),dtype=np.int8))
print(np.ones((5),int)) # shape이기때문에 괄호가 들어가야함
print(np.ones((2,3)))

[1 1 1 1 1]
[1 1 1 1 1]
[[1. 1. 1.]
 [1. 1. 1.]]


In [58]:
print(np.empty(shape = (10,),dtype = np.int32))
print(np.empty((2,5),np.int8))

[10  9  8  7  6  5  4  3  2  1]
[[1 1 1 1 0]
 [1 1 1 1 1]]


In [62]:
# 동일한 형태의 0 행렬 만들기
matrix = np.arange(24).reshape(4,6)
print(np.zeros_like(matrix))

# 동일한 형태의 1 행렬 만들기
matrix = np.arange(-2,2,0.2,).reshape(2,10)
print(np.ones_like(matrix))

# 동일한 형태의 empty 행렬 만들기
matrix = np.arange(30).reshape(5,6)
print(np.empty_like(matrix))

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[3801155 5570652 6619251 7536754 6357084 7143524]
 [7209065 3014748 7340137 7602297 7274600 6029422]
 [7471216 6684783 7077993 6226021 6619236 6357094]
 [7078005 6029428 6881384 7602291 7471215 3014777]
 [7405683 6881388 6619252 7798829 7077985       0]]


In [66]:
# 단위 행렬 생성
print(np.identity(5, dtype=np.str_))
print(np.identity(2))

[['1' '' '' '' '']
 ['' '1' '' '' '']
 ['' '' '1' '' '']
 ['' '' '' '1' '']
 ['' '' '' '' '1']]
[[1. 0.]
 [0. 1.]]


In [78]:
# 대각선이 1로 채워지는 행렬
# 대각선의 시작 위치 지정 가능
# 정사각행렬도 아님
# np.eye(size, M, k, dtype)
print(np.eye(5,dtype=np.int8))
print(np.eye(5,k=-1))
print(np.eye(5,M=10,k=4))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]
[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


In [83]:
# 입력 값으로 채워지는 행렬
# np.full((shape),value)
print(np.full((2,5),3))
print(np.full((5,4),'a'))

[[3 3 3 3 3]
 [3 3 3 3 3]]
[['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']]


In [137]:
import random

print(random.random())
print(random.randint(0,10))

0.8991211126783976
6


In [184]:
# 주어진 범위 안에서 랜덤값 뽑기
# 0~5 사이
print(np.random.randint(6))

# 1~19 사이
print(np.random.randint(1,20))

# 두개뽑기
print(np.random.randint(1,20,2))

0
17
[12  5]


In [187]:
# 랜덤한 값으로 채워지는 배열
# 0~1 의 값을 출력
print(np.random.rand(3))
print(np.random.rand(3,2))

[0.38162482 0.38143047 0.07202866]
[[0.40235549 0.79432096]
 [0.52306231 0.16163779]
 [0.76702988 0.9747341 ]]


In [189]:
# 음수도 포함
print(np.random.randn(3))
print(np.random.randn(3,2))

[-1.00493758 -1.05214977 -0.6763674 ]
[[ 0.71597847 -2.8014766 ]
 [-0.16337697  1.40119146]
 [ 0.66594333  0.54278561]]


In [200]:
# 모든 요소 더하기
matrix = np.arange(1, 7).reshape(2,3)
print(matrix.sum()) 

print(matrix.sum(axis=0)) # 행끼리 더하기(위 아래)
print(matrix.sum(axis=1)) # 열끼리 더하기(좌 우)

21
[5 7 9]
[ 6 15]


In [201]:
# 3차언 배열 합
tensor = np.arange(1,19).reshape(3,2,3)
print(tensor)
print(tensor.sum())

print(tensor.sum(axis=0)) # np.sum(tensor,axis=0)
print(tensor.sum(axis=1))
print(tensor.sum(axis=2))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
171
[[21 24 27]
 [30 33 36]]
[[ 5  7  9]
 [17 19 21]
 [29 31 33]]
[[ 6 15]
 [24 33]
 [42 51]]


In [198]:
# 평균 - 사용법은 합과 동일
print(matrix.mean())
print(matrix.mean(axis=0))
print(matrix.mean(axis=1))

3.5
[2.5 3.5 4.5]
[2. 5.]


In [204]:
# 표준편차
print(matrix.std())
print(matrix.std(axis=0))
print(matrix.std(axis=1))

1.707825127659933
[1.5 1.5 1.5]
[0.81649658 0.81649658]


In [208]:
# 지수
print(np.exp(matrix))

# 로그
print(np.log(matrix))

# 제곱근
print(np.sqrt(matrix))

# 삼각함수
print(np.sin(matrix))
print(np.cos(matrix))
print(np.tan(matrix))

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]]


In [219]:
# 1차원 배열 정렬
# randint를 사용하여 1~100 숫자 중 5개를 뽑아 배열 생성
vector = np.array([np.random.randint(1,101)
                   for n in range(5)])
print(vector)

print(np.sort(vector))       # 오름차순으로 정렬
print(np.sort(vector)[::-1]) # 내림차순으로 정렬

[86 39 65 84 22]
[22 39 65 84 86]
[86 84 65 39 22]


In [228]:
# 2차원 배열 정렬
# randint를 사용하여 1~100 숫자 중 20개를 뽑아 배열 생성
matrix = np.array([np.random.randint(1,101) 
                   for n in range(20)]).reshape(4,5)
print(matrix)

print(np.sort(matrix))           # 열 기준으로 정렬
print(np.sort(matrix, axis = 0)) # 행 기준으로 정렬

[[19 93 66 69 36]
 [81 42 21 74 73]
 [72 76  5 57  8]
 [10 38 88 39 39]]
[[19 36 66 69 93]
 [21 42 73 74 81]
 [ 5  8 57 72 76]
 [10 38 39 39 88]]
[[10 38  5 39  8]
 [19 42 21 57 36]
 [72 76 66 69 39]
 [81 93 88 74 73]]


In [237]:
# 배열 합치기
# 수직으로 합치기
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])

print(np.vstack([vector1, vector2]))

[[1 2 3]
 [4 5 6]]


In [235]:
# 수평으로 합치기
vector1 = np.array([1,2,3]).reshape(3,1)
vector2 = np.array([4,5,6]).reshape(3,1)

print(np.hstack([vector1, vector2]))

[[1 4]
 [2 5]
 [3 6]]


In [242]:
# 배열 합치기
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])
print(np.concatenate([vector1, vector2], axis=0)) # 1차원은 수직으로 결합이 안됨

vector1 = np.array([1,2,3]).reshape(3,1)
vector2 = np.array([4,5,6]).reshape(3,1)
print(np.concatenate([vector1, vector2], axis=1))

[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]


In [251]:
# 매트릭스와 벡터합치기
matrix1 = np.array([[1,2,3],[1,2,3]]).reshape(3,2)
vector2 = np.array([4,5,6]).reshape(3,1)
print(matrix1)
print(vector2)
print(np.concatenate([matrix1, vector2], axis=1))

[[1 2]
 [3 1]
 [2 3]]
[[4]
 [5]
 [6]]
[[1 2 4]
 [3 1 5]
 [2 3 6]]


In [257]:
# 2개 이상의 배열을 수직, 수평으로 합치기
matrix1 = np.arange(1,5).reshape(2,2)
matrix2 = np.arange(5,9).reshape(2,2)
print(np.concatenate([matrix1, matrix2], axis=1))

[[1 2 5 6]
 [3 4 7 8]]


In [258]:
# 행/열 바꾸기
matrix3 = np.array([[5,6]])
print(matrix3)
print(matrix3.transpose())
print(matrix3.T)

[[5 6]]
[[5]
 [6]]
[[5]
 [6]]


In [264]:
print(np.concatenate([matrix1, matrix3]))
print(np.concatenate([matrix1, matrix3.T], axis=1))

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]


In [270]:
a = np.arange(1,11).reshape(2,5)
print(a)
print(np.argmax(a),np.argmin(a))
print(np.argmax(a, axis=0)) # 수직(열)방향으로 max값 index 찾기

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
9 0
[1 1 1 1 1]


In [273]:
b = np.array([[1,2,3,4],[2,3,4,1],[3,4,1,2]])
print(b)
print(np.argmax(b, axis = 1))
print(np.argmax(b, axis = 0))

[[1 2 3 4]
 [2 3 4 1]
 [3 4 1 2]]
[3 2 1]
[2 2 1 0]


In [277]:
# 배열 인덱싱(Fancy Index)
a = np.arange(1,11)
b = np.array([3,4,5,6])
print(a)
print(b)
print(a[b]) # 인덱스의 값을 가지는 배열을 통해 인덱싱

[ 1  2  3  4  5  6  7  8  9 10]
[3 4 5 6]
[4 5 6 7]


In [280]:
a = np.arange(10,20)
b = np.argmax(a)
print(a)
print(b)
print(a[b])

[10 11 12 13 14 15 16 17 18 19]
9
19
