In [3]:
import numpy as np

In [8]:
list1 = [1,2,3]
list2 = [4,5,6]
print(list1 + list2) # 리스트끼리 요소 연산은 불가능

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1 + arr2) # 요소끼리 연산이 가능

[1, 2, 3, 4, 5, 6]
[5 7 9]


In [11]:
# 모양이 같은 배열 연산
arr1 = np.arange(1, 7, dtype=np.float32).reshape(2,3)
arr2 = np.arange(11, 17, dtype=np.int32).reshape(2,3)
print(arr1 + arr2) # float와 int를 더하면 float가 됨
print(arr2 - arr1)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 ** arr2)
print(arr2 // arr1)
print(arr2 % arr1)

[[12. 14. 16.]
 [18. 20. 22.]]
[[10. 10. 10.]
 [10. 10. 10.]]
[[11. 24. 39.]
 [56. 75. 96.]]
[[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]]
[[1.00000000e+00 4.09600000e+03 1.59432300e+06]
 [2.68435456e+08 3.05175781e+10 2.82110991e+12]]
[[11.  6.  4.]
 [ 3.  3.  2.]]
[[0. 0. 1.]
 [2. 0. 4.]]


In [16]:
# 산술연산
print(np.add(arr1, arr2))
print(np.subtract(arr1, arr2))
print(np.multiply(arr1, arr2))
print(np.divide(arr1, arr2))

[[12. 14. 16.]
 [18. 20. 22.]]
[[-10. -10. -10.]
 [-10. -10. -10.]]
[[11. 24. 39.]
 [56. 75. 96.]]
[[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]]


In [35]:
# Broadcast - 연산하고자 하는 배열의 모양이 다른 경우의 연산
arr3 = np.arange(10).reshape(5,2)
arr3 = np.arange(10).reshape(2,5)
print(arr3 + arr4) # 배열의 모양이 다르기때문에 오류

NameError: name 'arr4' is not defined

In [36]:
scalar = 10
vector = np.array([1,2,3])
print(scalar + vector) # 자동으로 스칼라를 broadcast하여 벡터랑 연산이 가능하게 해줌

scalar = 10
matrix = np.array([[1,2,3],[4,5,6]])
print(scalar + matrix)

[11 12 13]
[[11 12 13]
 [14 15 16]]


In [24]:
scalar = 10
tensor = np.arange(1,19).reshape(3,2,3)
print(scalar + tensor)

[[[11 12 13]
  [14 15 16]]

 [[17 18 19]
  [20 21 22]]

 [[23 24 25]
  [26 27 28]]]


In [34]:
matrix = np.arange(1,10).reshape(3,3)
vector = np.arange(11,14).reshape(1,3)
print(matrix + vector) 
# 다른 차원끼리 모양만 맞으면 자동으로 broadcast 해줌

[[12 14 16]
 [15 17 19]
 [18 20 22]]


In [37]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3]).reshape(3,1)
print(arr1)
print(arr2)
print(arr1 + arr2) 
# 각각 broadcasting을 했을 때 두개가 동일한 모양이 나올 경우 연산 가능

np.broadcast(arr1, arr2) # 두 객체가 broadcast 가능한지 출력해주는 함수

[1 2 3]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [40]:
# 일반적인 곱연산
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
print(arr1 * arr2)

# np.dot 사용 행렬곱
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3]).T
print(np.dot(arr1,arr2))
print(arr1.dot(arr2))
print(arr1 @ arr2)

[1 4 9]
14
14
14


In [41]:
# 2차원 배열 행렬곱
arr3 = np.arange(1,7).reshape(2,3)
arr4 = np.arange(11,17).reshape(3,2)
print(np.dot(arr3, arr4))

[[ 82  88]
 [199 214]]
