In [1]:
import numpy as np

In [2]:
n = np.random.randn(3,5)
print(n)
n.tofile('n.npy')

[[-0.74160359  1.91947434 -0.65298245  1.20827282  0.38175896]
 [ 0.70169963 -0.30300404  0.25062766  0.07322505 -2.30441709]
 [-1.41848703 -1.26042362  2.22093525 -0.23725615  0.8116726 ]]


In [4]:
m = np.fromfile('n.npy').reshape(3,5) # shape(3,5)
print(m)

[[-0.74160359  1.91947434 -0.65298245  1.20827282  0.38175896]
 [ 0.70169963 -0.30300404  0.25062766  0.07322505 -2.30441709]
 [-1.41848703 -1.26042362  2.22093525 -0.23725615  0.8116726 ]]


In [5]:
np.save('n1.npy',n)
m1 = np.load('n1.npy')
print(m1)

[[-0.74160359  1.91947434 -0.65298245  1.20827282  0.38175896]
 [ 0.70169963 -0.30300404  0.25062766  0.07322505 -2.30441709]
 [-1.41848703 -1.26042362  2.22093525 -0.23725615  0.8116726 ]]


In [8]:
# n.tofile로 만든 n.npy는 np.load로 열리지않음
# no.tofile - no.fromfile
# np.save - np.load
np.load('n.npy')

ValueError: Cannot load file containing pickled data when allow_pickle=False